[phases.setup]
nixPkgs = ["python311", "openssl", "curl", "pipenv", "pip"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python3 app.py"
