name: Deploy to Railway

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v1.3.0
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
